version: '3.8'

services:
  vprodb:
    build: 
      context: ./Docker-file/db
    image: mohamednasser018/vprofiledb
    container_name: vprodb
    environment:
      MYSQL_ROOT_PASSWORD: "vprodbpass"
      MYSQL_DATABASE: "accounts"
    volumes:
      - vprodbdata:/var/lib/mysql
    ports:
     - "3306:3306"

  tomcat:
    build:
      context: ./tomcat
    container_name: tomcat
    ports:
      - "8080:8080"
    labels:
      project: "Vprofile"
      Author: "imran"
    depends_on:
      - mysql
  memcached:
    image: memcached
    container_name: vprocache01
    ports:
      - "11211:11211"
  rabbitmq:
    image: rabbitmq
    container_name: vpromq01
    ports:
      - "15672:15672"
    environment:  
      - RABBITMQ_DEFAULT_USE=guest
      - RABBITMQ_DEFAULT_PASS=guest
  vproapp:
    build: 
      context: ./Docker-file/app
    image: mohamednasser018/vprofileapp
    container_name: vproapp
    volumes:
      - vproappdata:/usr/local/tomcat/webapps
    ports:
     - "8080:8080"
  vproweb:
    build: 
      context: ./Docker-file/web
    image: mohamednasser018/vprofileweb
    container_name: vproweb
    ports:
     - "80:80"
volumes:
     vprodbdata: {}
     vproappdata: {}

